name: ci

on:
  workflow_dispatch: # 添加手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Lint CLI and run cargotests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            clients/cli
            proto

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./clients/cli

      - name: Format
        working-directory: clients/cli
        run: |
          rustfmt src/**/*.rs --check --edition 2021

      - name: Build
        working-directory: clients/cli
        run: |
          cargo build --release
          ls target/release


          
      - name: Save Binary
        working-directory: clients/cli
        run: |
          # 创建保存二进制文件的目录
          mkdir -p $GITHUB_WORKSPACE/artifacts
          # 定义二进制文件名
          BINARY_NAME="nexus-network"
          # 复制构建产物到 artifacts 目录
          cp target/release/$BINARY_NAME $GITHUB_WORKSPACE/artifacts/$BINARY_NAME
    
      
